<?php
if (($prolingua_slider_sc = prolingua_get_theme_option('front_page_title_shortcode')) != '' && strpos($prolingua_slider_sc, '[')!==false && strpos($prolingua_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$prolingua_anchor_icon = prolingua_get_theme_option('front_page_title_anchor_icon');	
		$prolingua_anchor_text = prolingua_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($prolingua_anchor_icon) || !empty($prolingua_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($prolingua_anchor_icon) ? ' icon="'.esc_attr($prolingua_anchor_icon).'"' : '')
											. (!empty($prolingua_anchor_text) ? ' title="'.esc_attr($prolingua_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($prolingua_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$prolingua_scheme = prolingua_get_theme_option('front_page_title_scheme');
				if (!prolingua_is_inherit($prolingua_scheme)) echo ' scheme_'.esc_attr($prolingua_scheme);
				echo ' front_page_section_paddings_'.esc_attr(prolingua_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$prolingua_css = '';
			$prolingua_bg_image = prolingua_get_theme_option('front_page_title_bg_image');
			if (!empty($prolingua_bg_image)) 
				$prolingua_css .= 'background-image: url('.esc_url(prolingua_get_attachment_url($prolingua_bg_image)).');';
			if (!empty($prolingua_css))
				echo ' style="' . esc_attr($prolingua_css) . '"';
	?>><?php
		// Add anchor
		$prolingua_anchor_icon = prolingua_get_theme_option('front_page_title_anchor_icon');	
		$prolingua_anchor_text = prolingua_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($prolingua_anchor_icon) || !empty($prolingua_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($prolingua_anchor_icon) ? ' icon="'.esc_attr($prolingua_anchor_icon).'"' : '')
											. (!empty($prolingua_anchor_text) ? ' title="'.esc_attr($prolingua_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (prolingua_get_theme_option('front_page_title_fullheight'))
				echo ' prolingua-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$prolingua_css = '';
				$prolingua_bg_mask = prolingua_get_theme_option('front_page_title_bg_mask');
				$prolingua_bg_color = prolingua_get_theme_option('front_page_title_bg_color');
				if (!empty($prolingua_bg_color) && $prolingua_bg_mask > 0)
					$prolingua_css .= 'background-color: '.esc_attr($prolingua_bg_mask==1
																		? $prolingua_bg_color
																		: prolingua_hex2rgba($prolingua_bg_color, $prolingua_bg_mask)
																	).';';
				if (!empty($prolingua_css))
					echo ' style="' . esc_attr($prolingua_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$prolingua_caption = prolingua_get_theme_option('front_page_title_caption');
				if (!empty($prolingua_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($prolingua_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post($prolingua_caption); ?></h1><?php
				}
			
				// Description (text)
				$prolingua_description = prolingua_get_theme_option('front_page_title_description');
				if (!empty($prolingua_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($prolingua_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post(wpautop($prolingua_description)); ?></div><?php
				}
				
				// Buttons
				if (prolingua_get_theme_option('front_page_title_button1_link')!='' || prolingua_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						prolingua_show_layout(prolingua_customizer_partial_refresh_front_page_title_button1_link());
						prolingua_show_layout(prolingua_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}